## Eigenvalores y eigenvectores 

In [27]:
import numpy as np 
np.random.seed(123)

In [28]:
sol = np.array([2,0,-1]).reshape(3,1)

In [29]:
r1 = np.random.randint(10,size=3)
r1

array([2, 2, 6])

In [30]:
r2 = np.random.randint(10,size=3)
r2

array([1, 3, 9])

In [31]:
a, b = np.random.randint(10, size=2)
r3 = a*r1+b*r2
a,b,r3

(6, 1, array([13, 15, 45]))

In [32]:
A = np.vstack((r1,r2,r3))
A

array([[ 2,  2,  6],
       [ 1,  3,  9],
       [13, 15, 45]])

In [33]:
A.shape

(3, 3)

In [34]:
B = A@sol 
B

array([[ -2],
       [ -7],
       [-19]])

In [35]:
B.shape

(3, 1)

In [36]:
S = np.hstack((A,B))
S

array([[  2,   2,   6,  -2],
       [  1,   3,   9,  -7],
       [ 13,  15,  45, -19]])

In [37]:
from sympy import Matrix

M = Matrix(S)
M

Matrix([
[ 2,  2,  6,  -2],
[ 1,  3,  9,  -7],
[13, 15, 45, -19]])

In [38]:
M_rref = M.rref()
M_rref

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 3, -3],
 [0, 0, 0,  0]]),
 (0, 1))

In [39]:
def gen_sol(t):
    return np.array([2, -3-3*t, t]).reshape(3,1)

s0 = gen_sol(-1)
s0

array([[ 2],
       [ 0],
       [-1]])

In [40]:
A@s0

array([[ -2],
       [ -7],
       [-19]])

In [41]:
Matrix(A).nullspace()

[Matrix([
 [ 0],
 [-3],
 [ 1]])]

In [42]:
Matrix(A)*Matrix(A).nullspace()[0]

Matrix([
[0],
[0],
[0]])

### Autovalores y autovectores

In [43]:
Matrix(A).eigenvals()

{25 - sqrt(609): 1, sqrt(609) + 25: 1, 0: 1}

In [44]:
Matrix(A).eigenvects()

[(0,
  1,
  [Matrix([
   [ 0],
   [-3],
   [ 1]])]),
 (25 - sqrt(609),
  1,
  [Matrix([
   [    sqrt(609)/77 + 5/11],
   [-6*sqrt(609)/77 - 19/11],
   [                      1]])]),
 (sqrt(609) + 25,
  1,
  [Matrix([
   [    5/11 - sqrt(609)/77],
   [-19/11 + 6*sqrt(609)/77],
   [                      1]])])]

In [45]:
Matrix(A).eigenvects()[0][2][0]

Matrix([
[ 0],
[-3],
[ 1]])

In [46]:
### Utilizando Numpy

eigval, eigvec = np.linalg.eig(A)

In [47]:
eigval

array([ 4.96779254e+01,  3.22074641e-01, -4.66468557e-17])

In [48]:
eigvec

array([[-1.30433900e-01, -2.00617139e-01,  6.85866393e-17],
       [-1.90399668e-01,  9.44854701e-01, -9.48683298e-01],
       [-9.73003065e-01, -2.58848136e-01,  3.16227766e-01]])

In [49]:
eigvec[:,2]

array([ 6.85866393e-17, -9.48683298e-01,  3.16227766e-01])

In [50]:
c = eigvec[:,2][2]
c

0.31622776601683783

In [51]:
eigvec[:,2]/c

array([ 2.16889997e-16, -3.00000000e+00,  1.00000000e+00])

In [52]:
A@eigvec[:,2]

array([-6.66133815e-16, -1.33226763e-15, -5.32907052e-15])