### Eigenvalores y eigenvectores

[Matrices - SymPy 1.13.0rc2 documentation](https://docs.sympy.org/latest/tutorials/intro-tutorial/matrices.html#eigenvalues-eigenvectors-and-diagonalization)

In [116]:
from sympy import Matrix

D = Matrix([[-1,0,0], [0,1,0], [0,0,1]])
D 

Matrix([
[-1, 0, 0],
[ 0, 1, 0],
[ 0, 0, 1]])

In [117]:
P = Matrix([[1,1,1], [1,2,3], [1,3,6]])
P.det()

1

In [118]:
A = P*D*P.inv()
A 

Matrix([
[-5, 6, -2],
[-6, 7, -2],
[-6, 6, -1]])

In [119]:
A.eigenvals()

{-1: 1, 1: 2}

In [120]:
A.eigenvects()

[(-1,
  1,
  [Matrix([
   [1],
   [1],
   [1]])]),
 (1,
  2,
  [Matrix([
   [1],
   [1],
   [0]]),
   Matrix([
   [-1/3],
   [   0],
   [   1]])])]

In [121]:
l1 = A.eigenvects()[0][0]
l1

-1

In [122]:
m1 = A.eigenvects()[0][1]
m1 

1

In [123]:
e11 = A.eigenvects()[0][2][0]
e11

Matrix([
[1],
[1],
[1]])

In [124]:
l2 = A.eigenvects()[1][0]
l2

1

In [125]:
m2 = A.eigenvects()[1][1]
m2

2

In [126]:
e21 = A.eigenvects()[1][2][0]
e21

Matrix([
[1],
[1],
[0]])

In [127]:
e22 = A.eigenvects()[1][2][1]
e22

Matrix([
[-1/3],
[   0],
[   1]])

In [128]:
A@e11 - l1*e11

Matrix([
[0],
[0],
[0]])

In [129]:
A@e21 - l2*e21

Matrix([
[0],
[0],
[0]])

In [130]:
A@e22 - l2*e22

Matrix([
[0],
[0],
[0]])

In [131]:
P, D = A.diagonalize()

In [132]:
P 

Matrix([
[1, 1, -1],
[1, 1,  0],
[1, 0,  3]])

In [133]:
D

Matrix([
[-1, 0, 0],
[ 0, 1, 0],
[ 0, 0, 1]])

## Cálculo de los eigenvalores y eigenvectores de una matriz cuadrada usando Scipy

[Linear algebra (scipy.linalg) — SciPy v1.13.1 Manual](https://docs.scipy.org/doc/scipy/reference/linalg.html#eigenvalue-problems)

In [134]:
A

Matrix([
[-5, 6, -2],
[-6, 7, -2],
[-6, 6, -1]])

In [135]:
import numpy as np


B = np.array(A).astype(np.float64)
B

array([[-5.,  6., -2.],
       [-6.,  7., -2.],
       [-6.,  6., -1.]])

In [136]:
from scipy.linalg import eigvals 

eigvals(B)

array([-1.+0.j,  1.+0.j,  1.+0.j])

In [137]:
from scipy.linalg import eig

eig(B)

(array([-1.+0.j,  1.+0.j,  1.+0.j]),
 array([[-0.57735027,  0.42640143, -0.57858426],
        [-0.57735027,  0.63960215, -0.71150227],
        [-0.57735027,  0.63960215, -0.39875402]]))

In [138]:
k1 = eig(B)[0][0]
k1 

(-1.0000000000000027+0j)

In [139]:
f1  = eig(B)[1][:,0]
f1 

array([-0.57735027, -0.57735027, -0.57735027])

In [140]:
B@f1 - k1*f1

array([-3.33066907e-16+0.j, -1.11022302e-16+0.j,  2.22044605e-16+0.j])

In [141]:
k2 = eig(B)[0][1]
k2 

(1.0000000000000013+0j)

In [142]:
f2 = eig(B)[1][:,1]
f2 

array([0.42640143, 0.63960215, 0.63960215])

In [143]:
B@f2 - k2*f2

array([1.72084569e-15+0.j, 9.99200722e-16+0.j, 1.55431223e-15+0.j])

In [144]:
k3 = eig(B)[0][2]
k3 

(0.9999999999999996+0j)

In [145]:
f3 = eig(B)[1][:,2]
f3

array([-0.57858426, -0.71150227, -0.39875402])

In [146]:
B@f3 - k3*f3

array([-3.33066907e-16+0.j, -7.77156117e-16+0.j, -6.10622664e-16+0.j])