# Sistemas de ecuaciones lineales
## Una introducción al álgebra lineal

En este notebook vamos a ver cómo resolver sistemas de ecuaciones lineales. Un sistema de ecuaciones lineales es un conjunto de ecuaciones de la forma:

$$
\begin{align*}
a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n &= b_1 \\
a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n &= b_2 \\
\vdots \\
a_{m1}x_1 + a_{m2}x_2 + \ldots + a_{mn}x_n &= b_m \\
\end{align*}
$$

Donde $a_{ij}$ son los coeficientes de las incógnitas $x_i$, $b_i$ son los términos independientes y $m$ y $n$ son los números de ecuaciones e incógnitas, respectivamente.

En notación matricial, el sistema anterior se puede escribir como:

$$
\begin{bmatrix}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn} \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix}
=
\begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m \\
\end{bmatrix}
$$

O simplemente $Ax = b$, donde $A$ es la matriz de coeficientes, $x$ es el vector de incógnitas y $b$ es el vector de términos independientes.

En este notebook vamos a ver cómo resolver sistemas de ecuaciones lineales de la forma $Ax = b$ utilizando la función `solve` de la librería `numpy`.

### Referencia 

Para una introducción más detallada sobre álgebra lineal, se recomienda el tutorial [Esencia del Álgebra Lineal - YouTube](https://www.youtube.com/playlist?list=PLIb_io8a5NB2DddFf-PwvZDCOUNT1GZoA)

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?si=Oth94Jv53XIg7PDy&amp;list=PLIb_io8a5NB2DddFf-PwvZDCOUNT1GZoA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## Operaciones matriciales

Para trabajar con matrices y vectores en Python, utilizaremos la librería `numpy`. A continuación, se muestra cómo definir matrices y vectores en `numpy`:

In [58]:
import numpy as np

In [59]:
# Creación de matrices
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
type(matrix1)

numpy.ndarray

In [61]:
# Otra forma de crear matrices
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
type(matrix2)

numpy.matrix

### Multiplicación de matrices	

Sean $A= \begin{pmatrix} a_{i,j} \end{pmatrix} $ y $B=\begin{pmatrix}b_{i,j}\end{pmatrix}$ dos matrices de tamaño $m \times n$ y $n \times p$, respectivamente. Entonces, el producto de A y B es una matriz de tamaño $m \times p$ cuyos elementos son:

$$
c_{ij} = \sum_{k=1}^{n} a_{i,k}b_{k,j}
$$


In [63]:
# Multiplicación matricial
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B


array([[19, 22],
       [43, 50]])

In [64]:
# Acceso a los elementos de una matriz
A[0,0]


1

También existe una multiplicación de matrices, elemento a elemento. En este caso, las dimensiones de $A$ y $B$ deben ser iguales. El resultado es una matriz $C$ de las mismas dimensiones que $A$ y $B$, cuyos elementos son:

$$
c_{i,j} = a_{i,j}\cdot b_{i,j}
$$


In [65]:
# Multiplicación elemento a elemento
A*B

array([[ 5, 12],
       [21, 32]])

In [66]:
A[0,1]


2

### Determinante de una matriz

El determinante de una matriz cuadrada $A$ de tamaño $n \times n$ se denota como $|A|$ o $\text{det}(A)$. Para una matriz de tamaño $2 \times 2$, el determinante es:

$$
\begin{vmatrix}
a & b \\
c & d \\
\end{vmatrix}
= ad - bc
$$

De manera recursiva, el determinante de una matriz de tamaño $n \times n$ se puede calcular como:

$$
\text{det}(A) = \sum_{j=1}^{n} (-1)^{1+j}a_{1,j}M_{1,j}
$$

Donde $M_{1,j}$ es el determinante de la matriz $A$ sin la fila 1 y la columna $j$.


In [67]:
# Determinante de una matriz
np.linalg.det(A)


-2.0000000000000004

#### Propiedades del determinante

1. El determinante de una matriz triangular es el producto de los elementos de la diagonal principal.
2. Si una matriz tiene una fila o columna de ceros, entonces su determinante es cero.
3. Si dos filas o columnas de una matriz son iguales, entonces su determinante es cero.
4. Si se intercambian dos filas o columnas de una matriz, el determinante cambia de signo.
5. Si una fila o columna de una matriz se multiplica por un escalar, el determinante se multiplica por el mismo escalar.
6. Si una matriz se puede expresar como la suma de dos matrices, entonces su determinante es la suma de los determinantes de las dos matrices.
7. El determinante de una matriz multiplicada por otra matriz es igual al producto de los determinantes de las dos matrices.
8. El determinante de la inversa de una matriz es el inverso del determinante de la matriz original.
9. El determinante de la transpuesta de una matriz es igual al determinante de la matriz original.
10. El determinante de una matriz es igual al determinante de su matriz triangular asociada.


### Matrix identidad

La matriz identidad de tamaño $n \times n$ es una matriz cuadrada con unos en la diagonal principal y ceros en el resto de las entradas. Se denota como $I_n$ o simplemente $I$. Para cualquier matriz $A$ de tamaño $n \times n$, se cumple que:

$$
A \cdot I = I \cdot A = A
$$

In [68]:
# Matriz identidad
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [69]:
I2@A


array([[1., 2.],
       [3., 4.]])

In [70]:
A@I2


array([[1., 2.],
       [3., 4.]])

### Transpuesta de una matriz

La transpuesta de una matriz $A$ de tamaño $m \times n$ se denota como $A^T$ y es una matriz de tamaño $n \times m$ cuyas entradas son:

$$
a_{ij}^T = a_{ji}
$$

In [71]:
# Transpuesta de una matriz
A.T


array([[1, 3],
       [2, 4]])

In [72]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

### Inversa de una matriz

La inversa de una matriz cuadrada $A$ de tamaño $n \times n$ se denota como $A^{-1}$ y cumple que:

$$
A \cdot A^{-1} = A^{-1} \cdot A = I
$$


In [73]:
# Inversa de una matriz
C = np.linalg.inv(A)
C


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [74]:
A@C


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [75]:
C@A


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

### Resolución de sistemas de ecuaciones lineales con matrices inversas

Para resolver un sistema de ecuaciones lineales $Ax = b$, se puede utilizar la inversa de la matriz $A$:

$$
x = A^{-1}b
$$

siempre y cuando la matriz $A$ sea invertible.

In [78]:
A = np.array([[2, 1],
              [3, 2]])

b = np.array([8,11])

x = np.linalg.inv(A) @ b

x 


array([ 5., -2.])

In [79]:
# Comprobación

A @ x - b

array([ 0.00000000e+00, -1.77635684e-15])

In [80]:
np.isclose(A @ x, b)

array([ True,  True])

### Resolución de sistemas de ecuaciones lineales con la función `solve` de `numpy`

La función `solve` de `numpy` permite resolver sistemas de ecuaciones lineales de la forma $Ax = b$ de manera más eficiente. A continuación, se muestra cómo utilizar esta función:

In [76]:
import numpy as np

A = np.array([[2, 1],
              [3, 2]])
b = np.array([8, 11])

x = np.linalg.solve(A, B)

print("Solution (x, y):", x)

A @ x

Solution (x, y): [ 5. -2.]


array([ 8., 11.])