In [23]:
# Álgebra lineal con NumPy
## Operaciones con matrices

import numpy as np

# Crear una matriz
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [24]:
# Crear una matriz de ceros
B = np.zeros((2, 2))
print(B)

[[0. 0.]
 [0. 0.]]


In [25]:
# Crear una matriz de unos
C = np.ones((2, 2))
print(C)

[[1. 1.]
 [1. 1.]]


In [26]:
# Crear una matriz identidad
D = np.eye(2)
print(D)

[[1. 0.]
 [0. 1.]]


In [27]:
# Suma de matrices
E = A + C
print(E)

[[2. 3.]
 [4. 5.]]


In [28]:
# Resta de matrices
F = A - C
print(F)

[[0. 1.]
 [2. 3.]]


In [29]:
# Multiplicación de matrices
G = A @ C
print(G)

[[3. 3.]
 [7. 7.]]


In [30]:
# Multiplicación de matrices por un escalar
H = 2 * A
print(H)

[[2 4]
 [6 8]]


In [31]:
# Transpuesta de una matriz
I = A.T
print(I)

[[1 3]
 [2 4]]


In [32]:
# Determinante de una matriz
det_A = np.linalg.det(A)
print(det_A)

-2.0000000000000004


In [33]:
# Inversa de una matriz
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
# Traza de una matriz
tr_A = np.trace(A)
print(tr_A)

5


In [35]:
# Norma de una matriz
norm_A = np.linalg.norm(A)
print(norm_A)

5.477225575051661


In [36]:
# Sistema de ecuaciones lineales

# Resolver el sistema de ecuaciones lineales
# 2x + 3y = 5
# 4x + 5y = 6

A = np.array([[2, 3], [4, 5]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[-3.5  4. ]


In [37]:
# Verificación
print(A @ x)

[5. 6.]


In [38]:
# Valores y vectores propios

# Calcular los valores y vectores propios
A = np.array([[1, 2], [3, 4]])
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)
print(eigvecs)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [40]:
v0 = eigvecs[:, 0]
l0 = eigvals[0]

l0*v0

array([ 0.30697009, -0.21062466])

In [45]:
A @ v0

array([ 0.30697009, -0.21062466])