# Espacios nulos

In [1]:
import numpy as np 
np.random.seed(123)

In [2]:
sol = np.array([2,0,-1]).reshape(3,1)

In [3]:
r1 = np.random.randint(10,size=3)
r1

array([2, 2, 6])

In [4]:
r1 = np.array([2,2,6])
r1

array([2, 2, 6])

In [5]:
r2 = np.random.randint(10,size=3)
r2

array([1, 3, 9])

In [6]:
r2 = np.array([1,3,9])
r2

array([1, 3, 9])

In [7]:
a, b = np.random.randint(10, size=2)
r3 = a*r1+b*r2
a,b,r3

(6, 1, array([13, 15, 45]))

In [8]:
a = 6
b = 1
r3 =  a*r1 + b*r2
r3

array([13, 15, 45])

In [9]:
A = np.vstack((r1,r2,r3))
A

array([[ 2,  2,  6],
       [ 1,  3,  9],
       [13, 15, 45]])

In [10]:
A.shape

(3, 3)

In [11]:
B = A@sol 
B

array([[ -2],
       [ -7],
       [-19]])

In [12]:
B.shape

(3, 1)

In [13]:
S = np.hstack((A,B))
S

array([[  2,   2,   6,  -2],
       [  1,   3,   9,  -7],
       [ 13,  15,  45, -19]])

In [14]:
from sympy import Matrix

M = Matrix(S)
M

Matrix([
[ 2,  2,  6,  -2],
[ 1,  3,  9,  -7],
[13, 15, 45, -19]])

In [15]:
M_rref = M.rref()
M_rref

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 3, -3],
 [0, 0, 0,  0]]),
 (0, 1))

In [16]:
def gen_sol(t):
    return np.array([2, -3-3*t, t]).reshape(3,1)

s0 = gen_sol(-1)
s0

array([[ 2],
       [ 0],
       [-1]])

In [17]:
A@s0

array([[ -2],
       [ -7],
       [-19]])

In [18]:
Matrix(A).nullspace()

[Matrix([
 [ 0],
 [-3],
 [ 1]])]

In [19]:
Matrix(A)*Matrix(A).nullspace()[0]

Matrix([
[0],
[0],
[0]])