# Espacios nulos

In [76]:
import numpy as np

In [77]:
A = np.array([[ 2,  2,  6],
       [ 1,  3,  9],
       [13, 15, 45]])

In [78]:
A.shape

(3, 3)

In [79]:
np.linalg.det(A)

-6.832141690000961e-17

In [81]:
B = np.array([[ -2],
       [ -7],
       [-19]])

In [82]:
B.shape

(3, 1)

In [83]:
S = np.hstack((A,B))
S

array([[  2,   2,   6,  -2],
       [  1,   3,   9,  -7],
       [ 13,  15,  45, -19]])

In [84]:
from sympy import Matrix

M = Matrix(S)
M

Matrix([
[ 2,  2,  6,  -2],
[ 1,  3,  9,  -7],
[13, 15, 45, -19]])

In [85]:
M_rref = M.rref()
M_rref

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 3, -3],
 [0, 0, 0,  0]]),
 (0, 1))

In [86]:
def gen_sol(t):
    return np.array([2, -3-3*t, t]).reshape(3,1)

s0 = gen_sol(-1)
s0

array([[ 2],
       [ 0],
       [-1]])

In [87]:
A@s0

array([[ -2],
       [ -7],
       [-19]])

In [88]:
Matrix(A).nullspace()

[Matrix([
 [ 0],
 [-3],
 [ 1]])]

In [89]:
Matrix(A)*Matrix(A).nullspace()[0]

Matrix([
[0],
[0],
[0]])