In [1]:
import numpy as np

In [2]:
# Creación de matrices
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
type(matrix1)

numpy.ndarray

In [4]:
# Otra forma de crear matrices
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
type(matrix2)

numpy.matrix

In [6]:
# Multiplicación matricial
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B


array([[19, 22],
       [43, 50]])

In [7]:
# Multiplicación elemento a elemento
A*B

array([[ 5, 12],
       [21, 32]])

In [8]:
# Determinante de una matriz
np.linalg.det(A)


-2.0000000000000004

In [9]:
# Acceso a los elementos de una matriz
A[0,0]


1

In [10]:
A[0,1]


2

In [11]:
# Matriz identidad
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [12]:
I2@A


array([[1., 2.],
       [3., 4.]])

In [13]:
A@I2


array([[1., 2.],
       [3., 4.]])

In [14]:
# Transpuesta de una matriz
A.T


array([[1, 3],
       [2, 4]])

In [15]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [16]:
# Inversa de una matriz
C = np.linalg.inv(A)
C


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
A@C


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [18]:
C@A


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [40]:
# Solución automática
import numpy as np

# Coefficient matrix A
A = np.array([[2, 1],
              [3, 2]])

# Right-hand side vector B
B = np.array([8, 11])

# Solve the linear system of equations
solution = np.linalg.solve(A, B)

# The solution contains the values for the variables
print("Solution (x, y):", solution)

A @ solution

Solution (x, y): [ 5. -2.]


array([ 8., 11.])