In [1]:
# Numpy 

# Numpy es una librería de Python que se utiliza para trabajar con arreglos multidimensionales.
# Se utiliza para realizar operaciones matemáticas y lógicas con estos arreglos.
# Numpy es un acrónimo de "Numerical Python".

# Instalación de Numpy
# Para instalar Numpy, se utiliza el siguiente comando:
# pip install numpy

# Importar Numpy
# Para utilizar Numpy, se debe importar la librería:
import numpy as np

In [2]:
# Crear un arreglo de Numpy
# Para crear un arreglo de Numpy, se utiliza la función array().
# El siguiente ejemplo crea un arreglo de Numpy con 5 elementos:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
# Tipo de datos
# Numpy almacena los elementos de un arreglo en un tipo de datos específico.
# Se puede especificar el tipo de datos al crear un arreglo.
# El siguiente ejemplo crea un arreglo de Numpy con el tipo de datos string:
arr = np.array([1, 2, 3, 4, 5], dtype='float')
print(type(arr[0]))

<class 'numpy.float64'>


In [8]:
# Dimensiones de un arreglo
# Un arreglo de Numpy puede tener una o más dimensiones.
# Se puede especificar el número de dimensiones al crear un arreglo.
# Crear un arreglo de Numpy con 0 dimensiones
# Un arreglo de Numpy con 0 dimensiones se llama escalar.
# El siguiente ejemplo crea un arreglo de Numpy con 0 dimensiones:
arr = np.array(42)
print(arr)

42


In [9]:
# Crear un arreglo de Numpy con 1 dimensión
# Un arreglo de Numpy con 1 dimensión se llama vector.
# El siguiente ejemplo crea un arreglo de Numpy con 1 dimensión:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [10]:
# Crear un arreglo de Numpy con 2 dimensiones
# Un arreglo de Numpy con 2 dimensiones se llama matriz.
# El siguiente ejemplo crea un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
## Acceso a elementos de un arreglo
# Se puede acceder a los elementos de un arreglo de Numpy utilizando índices.
# El siguiente ejemplo accede al primer elemento de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [12]:
# Acceder a elementos de un arreglo de Numpy con 2 dimensiones
# Se puede acceder a los elementos de un arreglo de Numpy con 2 dimensiones utilizando índices.
# El siguiente ejemplo accede al elemento en la segunda fila y la tercera columna de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])

6


In [13]:
# Acceder a elementos de un arreglo de Numpy con 3 dimensiones
# Se puede acceder a los elementos de un arreglo de Numpy con 3 dimensiones utilizando índices.
# El siguiente ejemplo accede al elemento en la segunda dimensión, la segunda fila y la tercera columna de un arreglo de Numpy con 3 dimensiones:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 2])

12


In [14]:
# Slice de un arreglo
# Se puede acceder a un rango de elementos de un arreglo de Numpy utilizando slice.
# El siguiente ejemplo accede a los elementos del segundo al cuarto elemento de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [15]:
# Slice de un arreglo de Numpy con 2 dimensiones
# Se puede acceder a un rango de elementos de un arreglo de Numpy con 2 dimensiones utilizando slice.
# El siguiente ejemplo accede a los elementos de la segunda fila del primer elemento al segundo elemento de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 0:2])


[4 5]


In [16]:
# Slice de un arreglo de Numpy con 3 dimensiones
# Se puede acceder a un rango de elementos de un arreglo de Numpy con 3 dimensiones utilizando slice.
# El siguiente ejemplo accede a los elementos de la segunda dimensión, la segunda fila del primer elemento al segundo elemento de un arreglo de Numpy con 3 dimensiones:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 0:2])


[10 11]


In [17]:
# Dicing de un arreglo
# Se puede acceder a un rango de elementos de un arreglo de Numpy utilizando dicing.
# El siguiente ejemplo accede a los elementos de un arreglo de Numpy con un paso de 2:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])


[2 4]


In [18]:
# Dicing de un arreglo de Numpy con 2 dimensiones
# Se puede acceder a un rango de elementos de un arreglo de Numpy con 2 dimensiones utilizando dicing.
# El siguiente ejemplo accede a los elementos de un arreglo de Numpy con 2 dimensiones con un paso de 2:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr[0:2, 0:4:2])

[[1 3]
 [5 7]]


In [19]:
# Operaciones básicas de álgebra linea
# Numpy proporciona funciones para realizar operaciones básicas de álgebra lineal. 
# El siguiente ejemplo suma dos arreglos de Numpy:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.add(arr1, arr2)
print(arr)

[5 7 9]


In [20]:
# De manera alternativa, se puede utilizar el operador + para sumar dos arreglos de Numpy:
arr = arr1 + arr2
print(arr)

[5 7 9]


In [21]:
# Multiplicación de arreglos
# El siguiente ejemplo multiplica dos arreglos de Numpy:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.multiply(arr1, arr2)
print(arr)

[ 4 10 18]


In [22]:
# De manera alternativa, se puede utilizar el operador * para multiplicar dos arreglos de Numpy:
arr = arr1 * arr2
print(arr)

[ 4 10 18]


In [23]:
# Resta de arreglos
# El siguiente ejemplo resta dos arreglos de Numpy:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.subtract(arr1, arr2)   
print(arr)

[-3 -3 -3]


In [24]:
# De manera alternativa, se puede utilizar el operador - para restar dos arreglos de Numpy:
arr = arr1 - arr2
print(arr)

[-3 -3 -3]


In [25]:
# División de arreglos
# El siguiente ejemplo divide dos arreglos de Numpy:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.divide(arr1, arr2)
print(arr)


[0.25 0.4  0.5 ]


In [26]:
# De manera alternativa, se puede utilizar el operador / para dividir dos arreglos de Numpy:
arr = arr1 / arr2
print(arr)


[0.25 0.4  0.5 ]


In [27]:
## Agregaciones de arreglos
# Numpy proporciona funciones para realizar operaciones de agregación en arreglos.
# El siguiente ejemplo calcula la suma de los elementos de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [28]:
# Calcular la suma de los elementos de un arreglo de Numpy con 2 dimensiones
# El siguiente ejemplo calcula la suma de los elementos de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))  

21


In [29]:
# Calcular la suma de los elementos de un arreglo de Numpy con 2 dimensiones por columna
# El siguiente ejemplo calcula la suma de los elementos de un arreglo de Numpy con 2 dimensiones por columna:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr, axis=0))

[5 7 9]


In [30]:
# Calcular la suma de los elementos de un arreglo de Numpy con 2 dimensiones por fila
# El siguiente ejemplo calcula la suma de los elementos de un arreglo de Numpy con 2 dimensiones por fila:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr, axis=1))

[ 6 15]


In [31]:
# Calcular la media de los elementos de un arreglo de Numpy
# El siguiente ejemplo calcula la media de los elementos de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))

3.0


In [32]:
# Calcular la media de los elementos de un arreglo de Numpy con 2 dimensiones
# El siguiente ejemplo calcula la media de los elementos de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr))


3.5


In [33]:
# Calcular la media de los elementos de un arreglo de Numpy con 2 dimensiones por columna
# El siguiente ejemplo calcula la media de los elementos de un arreglo de Numpy con 2 dimensiones por columna:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))


[2.5 3.5 4.5]


In [34]:
# Calcular la media de los elementos de un arreglo de Numpy con 2 dimensiones por fila
# El siguiente ejemplo calcula la media de los elementos de un arreglo de Numpy con 2 dimensiones por fila:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=1))

[2. 5.]


In [35]:
# Calcular el máximo de los elementos de un arreglo de Numpy
# El siguiente ejemplo calcula el máximo de los elementos de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(np.max(arr))


5


In [36]:
# Calcular el máximo de los elementos de un arreglo de Numpy con 2 dimensiones
# El siguiente ejemplo calcula el máximo de los elementos de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr))

6


In [37]:
# Calcular el máximo de los elementos de un arreglo de Numpy con 2 dimensiones por columna
# El siguiente ejemplo calcula el máximo de los elementos de un arreglo de Numpy con 2 dimensiones por columna:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=0))

[4 5 6]


In [38]:
# Calcular el máximo de los elementos de un arreglo de Numpy con 2 dimensiones por fila
# El siguiente ejemplo calcula el máximo de los elementos de un arreglo de Numpy con 2 dimensiones por fila:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))

[3 6]


In [39]:
# Operaciones de broadcasting
# Numpy proporciona funciones para realizar operaciones de broadcasting en arreglos.
# El broadcasting permite realizar operaciones entre arreglos de diferentes formas.
# El siguiente ejemplo suma un escalar a un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 1)


[2 3 4 5 6]


In [40]:
# El siguiente ejemplo suma un arreglo de Numpy a otro arreglo de Numpy:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])
print(arr1 + arr2)


[ 2  4  6  8 10]


In [41]:
# El siguiente ejemplo suma un arreglo de Numpy con 2 dimensiones a otro arreglo de Numpy con 1 dimensión:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
print(arr1 + arr2)

[[2 4 6]
 [5 7 9]]
