In [14]:
# Estadística matemática con Numpy
import numpy as np

# Calculando la media
x = np.array([1, 2, 3, 4, 5])
mean = np.mean(x)
print(mean)

3.0


In [15]:
# Calculo de la media con datos faltantes
x = np.array([1, 2, 3, np.nan, 5])
mean = np.nanmean(x)
print(mean)

2.75


In [16]:
# Calculando la mediana
x = np.array([1, 2, 3, 4, 5])
median = np.median(x)
print(median)

3.0


In [17]:
# Calculo de la mediana con datos faltantes
x = np.array([1, 2, 3, np.nan, 5])
median = np.nanmedian(x)
print(median)


2.5


In [18]:
# Cálculo de la moda
x = np.array([1, 2, 3, 4, 5, 6, 6, 6])
# mode = np.argmax(np.bincount(x))
bincount = np.bincount(x)
print(bincount)

[0 1 1 1 1 1 3]


In [19]:
mode = np.argmax(bincount)
print(mode)

6


In [20]:
# Cálculo de la desviación estándar
x = np.array([1, 2, 3, 4, 5])
std = np.std(x)
print(std)

1.4142135623730951


In [21]:
# Manipulación y limpieza de datos

# Eliminando datos faltantes
x = np.array([1, 2, 3, np.nan, 5])
x = x[~np.isnan(x)]
print(x)

[1. 2. 3. 5.]


In [22]:
# Eliminando datos duplicados
x = np.array([1, 2, 3, 3, 4, 5, 5])
x = np.unique(x)
print(x)

[1 2 3 4 5]


In [23]:
# Eliminando datos atípicos
x = np.array([1, 2, 3, 4, 5])
x = x[x < 5]
print(x)

[1 2 3 4]


In [24]:
# Reemplazando datos faltantes
x = np.array([1, 2, 3, np.nan, 5])
x[np.isnan(x)] = np.nanmean(x)
print(x)

[1.   2.   3.   2.75 5.  ]


In [25]:
# Transformación de datos
# Normalización de datos
x = np.array([1, 2, 3, 4, 5])
normalized = (x - np.min(x)) / (np.max(x) - np.min(x))
print(normalized) 

[0.   0.25 0.5  0.75 1.  ]


In [26]:
# Estandarización de datos
x = np.array([1, 2, 3, 4, 5])
standardized = (x - np.mean(x)) / np.std(x)
print(standardized)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
