In [1]:
# Numpy 

# Numpy es una librería de Python que se utiliza para trabajar con arreglos multidimensionales.
# Se utiliza para realizar operaciones matemáticas y lógicas con estos arreglos.
# Numpy es un acrónimo de "Numerical Python".

# Instalación de Numpy
# Para instalar Numpy, se utiliza el siguiente comando:
# pip install numpy

# Importar Numpy
# Para utilizar Numpy, se debe importar la librería:
import numpy as np

In [2]:
# Crear un arreglo de Numpy
# Para crear un arreglo de Numpy, se utiliza la función array().
# El siguiente ejemplo crea un arreglo de Numpy con 5 elementos:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
# Tipo de datos
# Numpy almacena los elementos de un arreglo en un tipo de datos específico.
# Se puede especificar el tipo de datos al crear un arreglo.
# El siguiente ejemplo crea un arreglo de Numpy con el tipo de datos string:
arr = np.array([1, 2, 3, 4, 5], dtype='float')
print(type(arr[0]))

<class 'numpy.float64'>


In [8]:
# Dimensiones de un arreglo
# Un arreglo de Numpy puede tener una o más dimensiones.
# Se puede especificar el número de dimensiones al crear un arreglo.
# Crear un arreglo de Numpy con 0 dimensiones
# Un arreglo de Numpy con 0 dimensiones se llama escalar.
# El siguiente ejemplo crea un arreglo de Numpy con 0 dimensiones:
arr = np.array(42)
print(arr)

42


In [9]:
# Crear un arreglo de Numpy con 1 dimensión
# Un arreglo de Numpy con 1 dimensión se llama vector.
# El siguiente ejemplo crea un arreglo de Numpy con 1 dimensión:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [10]:
# Crear un arreglo de Numpy con 2 dimensiones
# Un arreglo de Numpy con 2 dimensiones se llama matriz.
# El siguiente ejemplo crea un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
## Acceso a elementos de un arreglo
# Se puede acceder a los elementos de un arreglo de Numpy utilizando índices.
# El siguiente ejemplo accede al primer elemento de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [12]:
# Acceder a elementos de un arreglo de Numpy con 2 dimensiones
# Se puede acceder a los elementos de un arreglo de Numpy con 2 dimensiones utilizando índices.
# El siguiente ejemplo accede al elemento en la segunda fila y la tercera columna de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])

6


In [13]:
# Acceder a elementos de un arreglo de Numpy con 3 dimensiones
# Se puede acceder a los elementos de un arreglo de Numpy con 3 dimensiones utilizando índices.
# El siguiente ejemplo accede al elemento en la segunda dimensión, la segunda fila y la tercera columna de un arreglo de Numpy con 3 dimensiones:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 2])

12


In [14]:
# Slice de un arreglo
# Se puede acceder a un rango de elementos de un arreglo de Numpy utilizando slice.
# El siguiente ejemplo accede a los elementos del segundo al cuarto elemento de un arreglo de Numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [15]:
# Slice de un arreglo de Numpy con 2 dimensiones
# Se puede acceder a un rango de elementos de un arreglo de Numpy con 2 dimensiones utilizando slice.
# El siguiente ejemplo accede a los elementos de la segunda fila del primer elemento al segundo elemento de un arreglo de Numpy con 2 dimensiones:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 0:2])


[4 5]


In [16]:
# Slice de un arreglo de Numpy con 3 dimensiones
# Se puede acceder a un rango de elementos de un arreglo de Numpy con 3 dimensiones utilizando slice.
# El siguiente ejemplo accede a los elementos de la segunda dimensión, la segunda fila del primer elemento al segundo elemento de un arreglo de Numpy con 3 dimensiones:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 0:2])


[10 11]
